### ISSUE TITLE
Add support for custom number of principal components to be included in the analysis.

### ISSUE THREAD

**Issue by kauralasoo** [kerimoff/qtlmap#5]
Also add support for a custom covariates file

**Comment by kerimoff** [comment]
Added new parameters to determine the number of Principal Components
Default values `[n_geno_pcs = 3, n_pheno_pcs = 6]`

to change the number of needed PCs use (numbers are just examples)
`--n_geno_pcs 4`
or
`--n_pheno_pcs 5`

Be sure that provided number of PCs are less than sample size
