### ISSUE TITLE
change the qtltools to fastQTL in nominal pass

### ISSUE THREAD

**Issue by kerimoff** [kerimoff/qtlmap#6]
Currently, QTLTools do not provide standart error. The changed version of fastQTL provides it. 

Assume that variantID will be in format of chr_pos_ref_alt and mutate new columns (chr, pos, ref, alt) from output file using variant_ID column.

Make sure that input of fastQTL is shaped like chr_pos_ref_alt varian_id. change it if the initial form in vcf is provided as rsid rather that chr_pos_ref_alt

**Comment by kauralasoo** [comment]
This has now been solved in branch V2. Will be merged to master later.
